### ISSUE TITLE
Support for vars and computed properties

### ISSUE THREAD

**Issue by davidkraus** [gilt/SwiftPoet#9]
Hey,

i'm trying to generate the following code for all of my data structs with your library:

```
extension GridPoint: Hashable {
    var hashValue: Int {
        return x.hashValue ^ y.hashValue &* 16777619
    }

    static func == (lhs: GridPoint, rhs: GridPoint) -> Bool {
        return lhs.x == rhs.x && lhs.y == rhs.y
    }
}
```
_from https://developer.apple.com/documentation/swift/hashable_ 

The extension and the equal function are easy to create but i have not found a way to generate vars or computed properties. Do you have plans adding this?

**Comment by kyle-dorman** [comment]
Hey David. This is possible. I just added a test to demonstrate. Let me know if you have any other questions.

https://github.com/gilt/SwiftPoet/blob/master/Tests/FileTests/FieldSpecTests.swift#L24
